### ISSUE TITLE
Moped doesn't start

### ISSUE THREAD

**Issue by AdUki** [martijnboland/moped#31]
Mopidy doesn't work while other clients are working fine. This is screenshot where it hangs:
![screen shot 2015-01-01 at 13 07 15](https://cloud.githubusercontent.com/assets/914609/5592134/2e86cd9e-91b7-11e4-9fc8-34c574a8c61d.png)

This is log with -vvv flag: http://pastebin.com/yudhY1bE

This is short log:

```
2015-01-01 12:08:26,649 INFO [7368:MainThread] mopidy.utils.process: Got SIGTERM signal
2015-01-01 12:08:26,652 INFO [7368:MainThread] mopidy.commands: Interrupted. Exiting...
2015-01-01 12:08:26,655 INFO [7368:MainThread] mopidy.commands: Stopping Mopidy frontends
2015-01-01 12:08:26,746 INFO [7368:MainThread] mopidy.commands: Stopping Mopidy core
2015-01-01 12:08:26,762 INFO [7368:MainThread] mopidy.commands: Stopping Mopidy backends
2015-01-01 12:08:26,802 INFO [7368:PodcastBackend-9] mopidy_podcast.backend: Stopping Mopidy-Podcast directories
2015-01-01 12:08:26,839 INFO [7368:SpotifyThread] mopidy_spotify.session_manager: Disconnected from Spotify
2015-01-01 12:08:26,882 INFO [7368:MainThread] mopidy.commands: Stopping Mopidy audio
2015-01-01 12:08:26,898 INFO [7368:MainThread] mopidy.commands: Stopping Mopidy mixer
2015-01-01 12:08:29,230 INFO [7445:MainThread] mopidy.__main__: Starting Mopidy 0.19.5
2015-01-01 12:08:30,255 INFO [7445:MainThread] mopidy.config: Loading config from: builtin defaults, /usr/share/mopidy/conf.d, /etc/mopidy/mopidy.conf, command line options
2015-01-01 12:08:30,530 INFO [7445:MainThread] mopidy.__main__: Enabled extensions: mopify, spotify, mpd, http, stream, spotify_tunigo, youtube, podcast-itunes, simple-webclient, softwaremixer, moped, musicbox_webclient, websettings, podcast, local, api_explorer
2015-01-01 12:08:30,531 INFO [7445:MainThread] mopidy.__main__: Disabled extensions: none
2015-01-01 12:08:31,568 INFO [7445:MainThread] mopidy.commands: Starting Mopidy mixer: SoftwareMixer
2015-01-01 12:08:31,572 INFO [7445:MainThread] mopidy.softwaremixer.mixer: Mixing using GStreamer software mixing
2015-01-01 12:08:31,583 INFO [7445:MainThread] mopidy.commands: Mixer volume set to 30
2015-01-01 12:08:31,586 INFO [7445:MainThread] mopidy.commands: Starting Mopidy audio
2015-01-01 12:08:31,597 INFO [7445:MainThread] mopidy.commands: Starting Mopidy backends: SpotifyTunigoBackend, SpotifyBackend, PodcastBackend, YoutubeBackend, LocalBackend, StreamBackend
2015-01-01 12:08:31,665 INFO [7445:SpotifyBackend-5] mopidy_spotify.backend: Mopidy uses SPOTIFY(R) CORE
2015-01-01 12:08:31,706 INFO [7445:Audio-2] mopidy.audio.actor: Audio output set to "autoaudiosink"
2015-01-01 12:08:31,754 INFO [7445:MainThread] mopidy_podcast.backend: Starting Mopidy-Podcast directories: iTunesDirectory, FeedsDirectory
2015-01-01 12:08:31,792 INFO [7445:MainThread] mopidy_podcast.backend: Refreshing Mopidy-Podcast directories
2015-01-01 12:08:32,052 INFO [7445:MainThread] mopidy.local.playlists: Loaded 0 local playlists from /var/lib/mopidy/playlists
2015-01-01 12:08:32,055 INFO [7445:MainThread] mopidy.local.json: No local library metadata cache found at /var/lib/mopidy/local/library.json.gz. Please run `mopidy local scan` to index your local music library. If you do not have a local music collection, you can disable the local backend to hide this message.
2015-01-01 12:08:32,080 INFO [7445:MainThread] mopidy.local.library: Loaded 0 local tracks using json
2015-01-01 12:08:32,087 INFO [7445:PodcastDirectoryActor-6] requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): itunes.apple.com
2015-01-01 12:08:32,231 INFO [7445:MainThread] mopidy.commands: Starting Mopidy core
2015-01-01 12:08:32,614 INFO [7445:MainThread] mopidy.commands: Starting Mopidy frontends: HttpFrontend, MpdFrontend
2015-01-01 12:08:32,658 INFO [7445:MainThread] mopidy.mpd.actor: MPD server running at [::ffff:127.0.0.1]:6600
2015-01-01 12:08:32,662 INFO [7445:HttpFrontend-15] mopidy.http.actor: HTTP server running at [::]:6680
2015-01-01 12:08:33,147 INFO [7445:SpotifyThread] mopidy_spotify.session_manager: Connected to Spotify
2015-01-01 12:08:33,540 INFO [7445:HttpServer] root: 304 GET /moped/ (192.168.3.110) 211.62ms
2015-01-01 12:08:33,673 INFO [7445:HttpServer] root: 304 GET /moped/assets/moped-0.4.2.js (192.168.3.110) 15.84ms
2015-01-01 12:08:33,691 INFO [7445:HttpServer] root: 304 GET /moped/assets/css/moped-0.4.2.css (192.168.3.110) 5.15ms
2015-01-01 12:08:33,762 INFO [7445:HttpServer] root: 304 GET /moped/assets/images/settings-icon.png (192.168.3.110) 5.11ms
2015-01-01 12:08:33,816 INFO [7445:HttpServer] root: 304 GET /moped/assets/images/ajax-loader.gif (192.168.3.110) 5.64ms
2015-01-01 12:08:45,356 INFO [7445:SpotifyThread] mopidy_spotify.session_manager: Loaded 13 Spotify playlists
```

**Comment by martijnboland** [comment]
Could you check the browser console log for errors?

**Comment by AdUki** [comment]
On chrome I have one error:
```
Error: Failed to construct 'WebSocket': The URL 'undefined' is invalid.
    at Error (native)
    at c.connect (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:9:20759)
    at new c (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:9:18901)
    at Object.start (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:18:2379)
    at new <anonymous> (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:17:19794)
    at d (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:13:4137)
    at Object.e [as instantiate] (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:13:4250)
    at http://simonpi.local:6680/moped/assets/moped-0.4.2.js:13:21322
    at http://simonpi.local:6680/moped/assets/moped-0.4.2.js:13:13852
    at f (http://simonpi.local:6680/moped/assets/moped-0.4.2.js:12:20548)
```

**Comment by AdUki** [comment]
After I found that on other browsers it is working fine, I just deleted cookies and after that it works :+1:
