### ISSUE TITLE
Status: {{connectionState}}

### ISSUE THREAD

**Issue by olemde** [martijnboland/moped#35]
Hi
thx for your moped-website.
I have entered the setting-site to see, how i can configure the mopidy from there. There was a button to check ...something and it appear another setting-screen with "Status: {{connectionState}}"  on the upper right corner. And now my mopidy does not react on any click (back, or home).

Has someone an idea what happens here and how i can fixe this

thx

Ole

**Comment by martijnboland** [comment]
Check the javascript console for errors (F12 or CMD-ALT-I in Chrome). When you see {{}} texts, it's usually a sign that some javascript had an error during execution.

**Comment by HLFH** [comment]
I got these issues related to this status: Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans'. This request has been blocked; the content must be served over HTTPS.
moped-0.4.2.js:9 Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://music.gitnote.eu/mopidy/ws'. This request has been blocked; this endpoint must be available over WSS.c.connect @ moped-0.4.2.js:9
moped-0.4.2.js:14 Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Error (native)
    at c.connect (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:20759)
    at new c (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:18901)
    at Object.start (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:18:2379)
    at new <anonymous> (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:17:19794)
    at d (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4137)
    at Object.e [as instantiate] (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4250)
    at https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:21322
    at https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:13852
    at f (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:12:20548)(anonymous function) @ moped-0.4.2.js:14

**Comment by HLFH** [comment]
I got these issues related to this status: 

```bash
Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans'. This request has been blocked; the content must be served over HTTPS.
moped-0.4.2.js:9 Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://music.gitnote.eu/mopidy/ws'. This request has been blocked; this endpoint must be available over WSS.c.connect @ moped-0.4.2.js:9
moped-0.4.2.js:14 Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Error (native)
    at c.connect (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:20759)
    at new c (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:18901)
    at Object.start (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:18:2379)
    at new <anonymous> (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:17:19794)
    at d (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4137)
    at Object.e [as instantiate] (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4250)
    at https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:21322
    at https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:13852
    at f (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:12:20548)(anonymous function) @ moped-0.4.2.js:14
```

**Comment by HLFH** [comment]
It seems related to this PR: https://github.com/andrenarchy/mopidy.js/commit/1e5ebe6059c44d02dae2fa88e7a6b577d5c2b77e

**Comment by martijnboland** [comment]
Thanks for the heads up.

**Comment by HLFH** [comment]
@martijnboland No I believe that @olemde and my issue are the same.

```bash
Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Open+Sans'. This request has been blocked; the content must be served over HTTPS.
moped-0.4.2.js:9 Mixed Content: The page at 'https://music.gitnote.eu/moped/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://music.gitnote.eu/mopidy/ws'. This request has been blocked; this endpoint must be available over WSS.21.c.connect @ moped-0.4.2.js:9
moped-0.4.2.js:14 Error: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Error (native)
    at c.21.c.connect (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:20759)
    at new c (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:9:18901)
    at Object.start (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:18:2379)
    at new <anonymous> (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:17:19794)
    at d (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4137)
    at Object.e [as instantiate] (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:4250)
    at $get (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:21322)
    at https://music.gitnote.eu/moped/assets/moped-0.4.2.js:13:13852
    at f (https://music.gitnote.eu/moped/assets/moped-0.4.2.js:12:20548)
'''

mopidy-moped does not seem to be ready for HTTPS & WebSocket Secure: a PR should be done for moped-0.4.2.js

**Comment by martijnboland** [comment]
So, is this fixed with the latest version?

**Comment by kemebaik** [comment]
[ solved ] clear everything on your web browser , chrome , firefox , iceweasel..
close web browser then start up your mopidy on moped web client.
