### ISSUE TITLE
Click to Play track from playlist error

### ISSUE THREAD

**Issue by jaPajaap** [martijnboland/moped#41]
I receive a js error when clicking on a track (in a spotify playlist).

Clicking the play button afterwards works fine.

```javascript
Potentially unhandled rejection [10] TypeError: undefined is not a function
    at http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:19:12604
    at D (http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:9:8715)
    at s.when (http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:9:12231)
    at n.run (http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:9:11013)
    at b._drain (http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:9:14178)
    at drain (http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:9:13766)
    at http://x.x.x.x:6680/moped/assets/moped-0.4.4.js:8:30203
```

**Comment by martijnboland** [comment]
You're probably using mopidy 1.0.0. This error is fixed with moped 0.5.0.
