### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cJrmid/Mopidy-Moped/

### ISSUE THREAD

**Issue by gerroon** [martijnboland/moped#74]
Hi

I am trying to install it on Debian Testing Mopidy 2.1.0

pip install Mopidy-Moped
Collecting Mopidy-Moped
  Downloading Mopidy-Moped-0.7.1.tar.gz (395kB)
    100% |████████████████████████████████| 399kB 1.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cJrmid/Mopidy-Moped/setup.py", line 42, in <module>
        'Topic :: Multimedia :: Sound/Audio :: Players',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 225, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/dist.py", line 257, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 2029, in require
        working_set.resolve(self.dist.requires(self.extras),env,installer))
      File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 592, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (certifi 2017.7.27.1 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('certifi==2016.9.26'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cJrmid/Mopidy-Moped/

**Comment by martijnboland** [comment]
There seems to be a version conflict with certifi module. Unfortunately I have no idea how to solve this kind of problems because I don't have any experience in the the python/pip area apart from making the Moped installer. Maybe someone else with more Python experience can chime in?
