### ISSUE TITLE
sudo pip install Mopidy-Moped doesn't work on Stretch

### ISSUE THREAD

**Issue by wt9bind** [martijnboland/moped#76]
I get the following when running:
`pi@SpotiPi:~ $ sudo pip install Mopidy-Moped
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
pi@SpotiPi:~ $ 
`
Please advise.

**Comment by kingosticks** [comment]
Lots of google hits for this, suggestion is to update pip. Did you try that?
https://stackoverflow.com/questions/37734499/install-wheel-on-raspberry-pi-2-failing-incompleteread
